;;****************************************************************
;;						BASE DE CONOCIMIENTO
;;****************************************************************
;;================NUMERO DE TUPLAS DE CONOCIMIENTO================
101
;;==========================CONOCIMIENTO==========================
((Class . Videogame)(Year . 1998)(Name . The-Legend-of-Zelda-Ocarina-of-Time)(Genero . Action-adventure)(Plataforma . Nintendo-64))
((Class . Videogame)(Year . 1984)(Name . Tetris)(Genero . Puzzle)(Plataforma . Elektronika-60))
((Class . Videogame)(Year . 1996)(Name . Super-Mario-64)(Genero . Platform)(Plataforma . Nintendo-64))
((Class . Videogame)(Year . 1991)(Name . The-Legend-of-Zelda-A-Link-to-the-Past)(Genero . Action-adventure)(Plataforma . Super-NES))
((Class . Videogame)(Year . 1995)(Name . Chrono-Trigger)(Genero . Role-playing)(Plataforma . Super-NES))
((Class . Videogame)(Year . 1997)(Name . Final-Fantasy-VII)(Genero . Role-playing)(Plataforma . PlayStation))
((Class . Videogame)(Year . 1991)(Name . Street-Fighter-II)(Genero . Fighting)(Plataforma . Arcade))
((Class . Videogame)(Year . 2004)(Name . Half-Life-2)(Genero . First-person-shooter)(Plataforma . PC))
((Class . Videogame)(Year . 1997)(Name . GoldenEye-007)(Genero . First-person-shooter)(Plataforma . Nintendo-64))
((Class . Videogame)(Year . 1990)(Name . Super-Mario-World)(Genero . Platform)(Plataforma . Super-NES))
((Class . Videogame)(Year . 1994)(Name . Super-Metroid)(Genero . Platform-adventure)(Plataforma . Super-NES))
((Class . Videogame)(Year . 2005)(Name . Resident-Evil-4)(Genero . Survival-horror)(Plataforma . GameCube))
((Class . Videogame)(Year . 1998)(Name . Metal-Gear-Solid)(Genero . Stealth)(Plataforma . PlayStation))
((Class . Videogame)(Year . 1992)(Name . Super-Mario-Kart)(Genero . Kart-racing)(Plataforma . Super-NES))
((Class . Videogame)(Year . 1997)(Name . Castlevania-Symphony-of-the-Night)(Genero . Platform-adventure)(Plataforma . PlayStation))
((Class . Videogame)(Year . 1988)(Name . Super-Mario-Bros-3)(Genero . Platform)(Plataforma . NES))
((Class . Videogame)(Year . 1985)(Name . Super-Mario-Bros)(Genero . Platform)(Plataforma . NES))
((Class . Videogame)(Year . 2007)(Name . BioShock)(Genero . First-person-shooter)(Plataforma . PC Xbox-360))
((Class . Videogame)(Year . 1994)(Name . Final-Fantasy-VI)(Genero . Role-playing)(Plataforma . Super-NES))
((Class . Videogame)(Year . 1996)(Name . Pokémon-Red-and-Blue)(Genero . Role-playing)(Plataforma . Game-Boy))
((Class . Videogame)(Year . 1998)(Name . StarCraft)(Genero . Real-time-strategy)(Plataforma . PC))
((Class . Videogame)(Year . 2005)(Name . Shadow-of-the-Colossus)(Genero . Action-adventure)(Plataforma . PlayStation-2))
((Class . Videogame)(Year . 1998)(Name . SoulCalibur)(Genero . Fighting)(Plataforma . Dreamcast))
((Class . Videogame)(Year . 1986)(Name . The-Legend-of-Zelda)(Genero . Action-adventure)(Plataforma . NES))
((Class . Videogame)(Year . 1993)(Name . Doom)(Genero . First-person-shooter)(Plataforma . PC))
((Class . Videogame)(Year . 1998)(Name . Half-Life)(Genero . First-person-shooter)(Plataforma . PC))
((Class . Videogame)(Year . 2000)(Name . Diablo-II)(Genero . Action-role-playing)(Plataforma . PC))
((Class . Videogame)(Year . 2004)(Name . World-of-Warcraft)(Genero . MMORPG)(Plataforma . PC))
((Class . Videogame)(Year . 2002)(Name . Metroid-Prime)(Genero . Action-adventure)(Plataforma . GameCube))
((Class . Videogame)(Year . 1995)(Name . Super-Mario-World-2-Yoshis-Island)(Genero . Platform)(Plataforma . Super-NES))
((Class . Videogame)(Year . 1996)(Name . Resident-Evil)(Genero . Survival-horror)(Plataforma . PlayStation))
((Class . Videogame)(Year . 2000)(Name . Deus-Ex)(Genero . Role-playing-shooter)(Plataforma . PC))
((Class . Videogame)(Year . 1980)(Name . Pac-Man)(Genero . Maze)(Plataforma . Arcade))
((Class . Videogame)(Year . 1981)(Name . Donkey-Kong)(Genero . Platform)(Plataforma . Arcade))
((Class . Videogame)(Year . 1987)(Name . Contra)(Genero . Run-and-gun)(Plataforma . Arcade))
((Class . Videogame)(Year . 2001)(Name . Halo-Combat-Evolved)(Genero . First-person-shooter)(Plataforma . Xbox))
((Class . Videogame)(Year . 1978)(Name . Space-Invaders)(Genero . Shoot-em-up)(Plataforma . Arcade))
((Class . Videogame)(Year . 1991)(Name . Sonic-the-Hedgehog)(Genero . Platform)(Plataforma . Genesis/Mega-Drive))
((Class . Videogame)(Year . 1998)(Name . Grim-Fandango)(Genero . Adventure)(Plataforma . PC))
((Class . Videogame)(Year . 2000)(Name . The-Legend-of-Zelda-Majoras-Mask)(Genero . Action-adventure)(Plataforma . Nintendo-64))
((Class . Videogame)(Year . 2001)(Name . Super-Smash-Bros-Melee)(Genero . Fighting)(Plataforma . GameCube))
((Class . Videogame)(Year . 2002)(Name . The-Legend-of-Zelda-The-Wind-Waker)(Genero . Action-adventure)(Plataforma . GameCube))
((Class . Videogame)(Year . 2010)(Name . Mass-Effect-2)(Genero . Role-playing-shooter)(Plataforma . PC Xbox-360))
((Class . Videogame)(Year . 2000)(Name . Counter-Strike)(Genero . First-person-shooter)(Plataforma . PC))
((Class . Videogame)(Year . 2013)(Name . The-Last-of-Us)(Genero . Survival-horror)(Plataforma . PlayStation-3))
((Class . Videogame)(Year . 1984)(Name . Punch-Out!!)(Genero . Sports)(Plataforma . Arcade))
((Class . Videogame)(Year . 1994)(Name . EarthBound)(Genero . Role-playing)(Plataforma . Super-NES))
((Class . Videogame)(Year . 2003)(Name . Star-Wars-Knights-of-the-Old-Republic)(Genero . Role-playing)(Plataforma . Xbox))
((Class . Videogame)(Year . 2007)(Name . Portal)(Genero . Puzzle-platformer)(Plataforma . PC Xbox-360))
((Class . Videogame)(Year . 2007)(Name . Super-Mario-Galaxy)(Genero . Platform)(Plataforma . Wii))
((Class . Videogame)(Year . 2011)(Name . Portal-2)(Genero . Puzzle-platformer)(Plataforma . PC PlayStation-3 Xbox-360))
((Class . Videogame)(Year . 1993)(Name . Secret-of-Mana)(Genero . Action-role-playing)(Plataforma . Super-NES))
((Class . Videogame)(Year . 1993)(Name . The-Legend-of-Zelda-Links-Awakening)(Genero . Action-adventure)(Plataforma . Game-Boy))
((Class . Videogame)(Year . 1997)(Name . Star-Fox-64)(Genero . Shoot-em-up)(Plataforma . Nintendo-64))
((Class . Videogame)(Year . 1998)(Name . Resident-Evil-2)(Genero . Survival-horror)(Plataforma . PlayStation))
((Class . Videogame)(Year . 2000)(Name . Perfect-Dark)(Genero . First-person-shooter)(Plataforma . Nintendo-64))
((Class . Videogame)(Year . 2001)(Name . Metal-Gear-Solid-2-Sons-of-Liberty)(Genero . Stealth)(Plataforma . PlayStation-2))
((Class . Videogame)(Year . 2007)(Name . Call-of-Duty-4-Modern-Warfare)(Genero . First-person-shooter)(Plataforma . PC PlayStation-3 Xbox-360))
((Class . Videogame)(Year . 2011)(Name . The-Elder-Scrolls-V-Skyrim)(Genero . Action-role-playing)(Plataforma . PC PlayStation-3 Xbox-360))
((Class . Videogame)(Year . 2011)(Name . Dark-Souls)(Genero . Action-role-playing)(Plataforma . PlayStation-3 Xbox-360))
((Class . Videogame)(Year . 1982)(Name . Ms-Pac-Man)(Genero . Maze)(Plataforma . Arcade))
((Class . Videogame)(Year . 1986)(Name . Metroid)(Genero . Platform-adventure)(Plataforma . NES))
((Class . Videogame)(Year . 2001)(Name . Advance-Wars)(Genero . Turn-based-tactics)(Plataforma . Game-Boy-Advance))
((Class . Videogame)(Year . 2001)(Name . Ico)(Genero . Action-adventure)(Plataforma . PlayStation-2))
((Class . Videogame)(Year . 2001)(Name . Silent-Hill-2)(Genero . Survival-horror)(Plataforma . PlayStation-2))
((Class . Videogame)(Year . 2003)(Name . Prince-of-Persia-The-Sands-of-Time)(Genero . Action-adventure)(Plataforma . PlayStation-2))
((Class . Videogame)(Year . 1987)(Name . Double-Dragon)(Genero . Beat-em-up)(Plataforma . Arcade))
((Class . Videogame)(Year . 1988)(Name . Mega-Man-2)(Genero . Platform)(Plataforma . NES))
((Class . Videogame)(Year . 1991)(Name . Final-Fantasy-IV)(Genero . Role-playing)(Plataforma . Super-NES))
((Class . Videogame)(Year . 1993)(Name . Gunstar-Heroes)(Genero . Run-and-gun)(Plataforma . Genesis/Mega-Drive))
((Class . Videogame)(Year . 1999)(Name . Shenmue)(Genero . Adventure)(Plataforma . Dreamcast))
((Class . Videogame)(Year . 2001)(Name . Final-Fantasy-X)(Genero . Role-playing)(Plataforma . PlayStation-2))
((Class . Videogame)(Year . 2001)(Name . Grand-Theft-Auto-III)(Genero . Action-adventure)(Plataforma . PlayStation-2))
((Class . Videogame)(Year . 2004)(Name . Metal-Gear-Solid-3-Snake-Eater)(Genero . Stealth)(Plataforma . PlayStation-2))
((Class . Videogame)(Year . 2006)(Name . Okami)(Genero . Action-adventure)(Plataforma . PlayStation-2))
((Class . Videogame)(Year . 1981)(Name . Galaga)(Genero . Shoot-em-up)(Plataforma . Arcade))
((Class . Videogame)(Year . 1994)(Name . Star-Wars-TIE-Fighter)(Genero . Space-simulation)(Plataforma . PC))
((Class . Videogame)(Year . 1996)(Name . Tomb-Raider)(Genero . Action-adventure)(Plataforma . Saturn))
((Class . Videogame)(Year . 1997)(Name . Final-Fantasy-Tactics)(Genero . Tactical-role-playing)(Plataforma . PlayStation))
((Class . Videogame)(Year . 2004)(Name . Grand-Theft-Auto-San-Andreas)(Genero . Action-adventure)(Plataforma . PlayStation-2))
((Class . Videogame)(Year . 2013)(Name . Grand-Theft-Auto-V)(Genero . Action-adventure)(Plataforma . PlayStation-3 Xbox-360))
((Class . Videogame)(Year . 2010)(Name . Red-Dead-Redemption)(Genero . Action-adventure)(Plataforma . PlayStation-3 Xbox-360))
((Class . Videogame)(Year . 1986)(Name . OutRun)(Genero . Racing)(Plataforma . Arcade))
((Class . Videogame)(Year . 1987)(Name . R-Type)(Genero . Shoot-em-up)(Plataforma . Arcade))
((Class . Videogame)(Year . 2008)(Name . Fallout-3)(Genero . Role-playing-shooter)(Plataforma . PC PlayStation-3 Xbox-360))
((Class . Videogame)(Year . 2009)(Name . Uncharted-2-Among-Thieves)(Genero . Action-adventure)(Plataforma . PlayStation-3))
((Class . Videogame)(Year . 2011)(Name . Minecraft)(Genero . Sandbox-survival)(Plataforma . PC))
((Class . Videogame)(Year . 1992)(Name . Sonic-the-Hedgehog-2)(Genero . Platform)(Plataforma . Genesis/Mega-Drive))
((Class . Videogame)(Year . 1993)(Name . Daytona-USA)(Genero . Racing)(Plataforma . Arcade))
((Class . Videogame)(Year . 2012)(Name . Journey)(Genero . Adventure)(Plataforma . PlayStation-3))
((Class . Videogame)(Year . 2011)(Name . Batman-Arkham-City)(Genero . Action-adventure)(Plataforma . PlayStation-3 Xbox-360))
((Class . Videogame)(Year . 2010)(Name . Super-Mario-Galaxy-2)(Genero . Platform)(Plataforma . Wii))
((Class . Videogame)(Year . 1996)(Name . Nights-into-Dreams)(Genero . Action)(Plataforma . Saturn))
((Class . Videogame)(Year . 1998)(Name . Xenogears)(Genero . Role-playing)(Plataforma . PlayStation))
((Class . Videogame)(Year . 2002)(Name . Kingdom-Hearts)(Genero . Action-role-playing)(Plataforma . PlayStation-2))
((Class . Videogame)(Year . 2008)(Name . Grand-Theft-Auto-IV)(Genero . Action-adventure)(Plataforma . PlayStation-3 Xbox-360))
((Class . Videogame)(Year . 1982)(Name . Robotron)(Genero . Shoot-em-up)(Plataforma . Arcade))
((Class . Videogame)(Year . 1984)(Name . Elite)(Genero . Space-simulation)(Plataforma . BBC-Micro))
((Class . Videogame)(Year . 1987)(Name . Tecmo-Bowl)(Genero . Sports)(Plataforma . Arcade))
((Class . Videogame)(Year . 2000)(Name . Skies-of-Arcadia)(Genero . Role-playing)(Plataforma . Dreamcast))
((Class . Videogame)(Year . 2012)(Name . Hotline-Miami)(Genero . Action)(Plataforma . PC))
((Class . Console)(Name . Magnavox-Odyssey)(Year . 1972)(Manufacturer/Country . Magnavox))
((Class . Console)(Name . Ping-O-Tronic)(Year . 1974)(Manufacturer/Country . Zanussi ))
((Class . Console)(Name . Atari-PONG)(Year . 1975)(Manufacturer/Country . Atari ))
((Class . Console)(Name . PC-50X-Family)(Year . 1975)(Manufacturer/Country . General-Instrument ))
((Class . Console)(Name . Tele-Spiel)(Year . 1975)(Manufacturer/Country . Philips ))
((Class . Console)(Name . Video-2000)(Year . 1975)(Manufacturer/Country . Interton ))
((Class . Console)(Name . Philips-Odyssey)(Year . 1976)(Manufacturer/Country . Philips ))
((Class . Console)(Name . Coleco-Telstar-Arcade)(Year . 1977)(Manufacturer/Country . Coleco ))
((Class . Console)(Name . Color-TV-Game)(Year . 1977)(Manufacturer/Country . Nintendo ))
((Class . Console)(Name . Fairchild-Channel-F)(Year . 1976)(Manufacturer/Country . Fairchild ))
((Class . Console)(Name . APF-MP1000)(Year . 1978)(Manufacturer/Country . APF ))
((Class . Console)(Name . RCA-Studio-II)(Year . 1977)(Manufacturer/Country . RCA ))
((Class . Console)(Name . Atari-2600)(Year . 1977)(Manufacturer/Country . Atari-Inc .  ))
((Class . Console)(Name . Bally-Astrocade)(Year . 1977)(Manufacturer/Country . Midway ))
((Class . Console)(Name . VC-4000)(Year . 1978)(Manufacturer/Country . Interton ))
((Class . Console)(Name . Magnavox-Odyssey²)(Year . 1978)(Manufacturer/Country . Magnavox / Philips ))
((Class . Console)(Name . APF-Imagination-Machine)(Year . 1979)(Manufacturer/Country . APF ))
((Class . Console)(Name . Intellivision)(Year . 1980)(Manufacturer/Country . Mattel ))
((Class . Console)(Name . PlayCable)(Year . 1981)(Manufacturer/Country . Mattel ))
((Class . Console)(Name . Bandai-Super-Vision-8000)(Year . 1979)(Manufacturer/Country . Bandai ))
((Class . Console)(Name . VTech-CreatiVision)(Year . 1981)(Manufacturer/Country . VTech ))
((Class . Console)(Name . Epoch-Cassette-Vision)(Year . 1981)(Manufacturer/Country . Epoch ))
((Class . Console)(Name . Arcadia-2001 (Leisure-Vision in-Canada))(Year . 1982)(Manufacturer/Country . Emerson-Radio ))
((Class . Console)(Name . Atari-5200 (US Only))(Year . 1982)(Manufacturer/Country . Atari-Inc .  ))
((Class . Console)(Name . ColecoVision)(Year . 1982)(Manufacturer/Country . Coleco ))
((Class . Console)(Name . Entex-Adventure-Vision)(Year . 1982)(Manufacturer/Country . Entex ))
((Class . Console)(Name . Vectrex)(Year . 1982)(Manufacturer/Country . General-Consumer-Electronics-/ Milton-Bradley-Company ))
((Class . Console)(Name . Compact-Vision-TV-Boy)(Year . 1983)(Manufacturer/Country . Gakken ))
((Class . Console)(Name . Pyuuta-Jr . )(Year . 1983)(Manufacturer/Country . Matsushita ))
((Class . Console)(Name . RDI-Halcyon)(Year . 1985)(Manufacturer/Country . RDI-Video-Systems ))
((Class . Console)(Name . PV-1000)(Year . 1983)(Manufacturer/Country . Casio ))
((Class . Console)(Name . Videopac-G7400)(Year . 1983)(Manufacturer/Country . Philips))
((Class . Console)(Name . Commodore-64-Games-System)(Year . 1990)(Manufacturer/Country . Commodore ))
((Class . Console)(Name . Amstrad-GX4000)(Year . 1990)(Manufacturer/Country . Amstrad ))
((Class . Console)(Name . Atari-7800)(Year . 1986)(Manufacturer/Country . Atari-Corporation ))
((Class . Console)(Name . Atari-XEGS)(Year . 1987)(Manufacturer/Country . Atari-Corporation ))
((Class . Console)(Name . Sega-SG-1000)(Year . 1983)(Manufacturer/Country . Sega ))
((Class . Console)(Name . Sega-Master-System)(Year . 1985)(Manufacturer/Country . Sega , Tec-Toy ))
((Class . Console)(Name . NES-/-Famicom)(Year . 1983)(Manufacturer/Country . Nintendo ))
((Class . Console)(Name . Family-Computer-Disk-System [2])(Year . 1986)(Manufacturer/Country . Nintendo ))
((Class . Console)(Name . My-Vision)(Year . 1983)(Manufacturer/Country . Nichibutsu ))
((Class . Console)(Name . Super-Cassette-Vision)(Year . 1984)(Manufacturer/Country . Epoch ))
((Class . Console)(Name . Zemmix)(Year . 1985)(Manufacturer/Country . Daewoo-Electronics ))
((Class . Console)(Name . Bridge-Companion)(Year . 1985)(Manufacturer/Country . BBC /-Heber ))
((Class . Console)(Name . Videosmarts)(Year . 1986)(Manufacturer/Country . Connor-Electronics  (1987-1988), VTech  (1989-1990)))
((Class . Console)(Name . ComputerSmarts)(Year . 1987)(Manufacturer/Country . Connor-Electronics ))
((Class . Console)(Name . Action-Max)(Year . 1987)(Manufacturer/Country . Worlds-of-Wonder ))
((Class . Console)(Name . Video-Challenger)(Year . 1987)(Manufacturer/Country . Tomy  / Bandai ))
((Class . Console)(Name . Video-Art)(Year . 1987)(Manufacturer/Country . LJN ))
((Class . Console)(Name . Sega-Genesis-/-Mega-Drive)(Year . 1988)(Manufacturer/Country . Sega ))
((Class . Console)(Name . Sega-CD-/-Mega-CD)(Year . 1992)(Manufacturer/Country . Sega ))
((Class . Console)(Name . Sega-32X --Add-on-to-Sega-Genesis)(Year . 1994)(Manufacturer/Country . Sega ))
((Class . Console)(Name . PC-Engine-/-TurboGrafx-16)(Year . 1987)(Manufacturer/Country . NEC ))
((Class . Console)(Name . PC-Engine2-/-SuperGrafx)(Year . 1989)(Manufacturer/Country . NEC ))
((Class . Console)(Name . Interactive-Vision)(Year . 1988)(Manufacturer/Country . View-Master-Ideal-Group-Inc . ))
((Class . Console)(Name . Socrates)(Year . 1988)(Manufacturer/Country . VTech ))
((Class . Console)(Name . Terebikko)(Year . 1988)(Manufacturer/Country . Bandai ))
((Class . Console)(Name . Neo-Geo)(Year . 1990)(Manufacturer/Country . SNK ))
((Class . Console)(Name . Sega-Pico)(Year . 1994)(Manufacturer/Country . Sega/ Majesco ))
((Class . Console)(Name . Neo-Geo-CD)(Year . 1994)(Manufacturer/Country . SNK ))
((Class . Console)(Name . Commodore-CDTV)(Year . 1991)(Manufacturer/Country . Commodore ))
((Class . Console)(Name . Memorex-VIS)(Year . 1992)(Manufacturer/Country . Memorex ))
((Class . Console)(Name . Super-NES-/-Super-Famicom)(Year . 1990)(Manufacturer/Country . Nintendo ))
((Class . Console)(Name . Satellaview [3])(Year . 1993)(Manufacturer/Country . Nintendo ))
((Class . Console)(Name . CD-i)(Year . 1991)(Manufacturer/Country . Philips ))
((Class . Console)(Name . TurboDuo-/-PC-Engine-Duo)(Year . 1991)(Manufacturer/Country . NEC ))
((Class . Console)(Name . Super-ACan)(Year . 1995)(Manufacturer/Country . Funtech ))
((Class . Console)(Name . Pioneer-LaserActive)(Year . 1993)(Manufacturer/Country . Pioneer-Corporation ))
((Class . Console)(Name . FM-Towns-Marty)(Year . 1993)(Manufacturer/Country . Fujitsu ))
((Class . Console)(Name . Apple-Bandai-Pippin)(Year . 1995)(Manufacturer/Country . Bandai /Apple-Inc .  ))
((Class . Console)(Name . PC-FX)(Year . 1994)(Manufacturer/Country . NEC ))
((Class . Console)(Name . Atari-Jaguar)(Year . 1993)(Manufacturer/Country . Atari-Corporation ))
((Class . Console)(Name . Atari-Jaguar-CD)(Year . 1995)(Manufacturer/Country . Atari-Corporation ))
((Class . Console)(Name . PlayStation)(Year . 1994)(Manufacturer/Country . Sony ))
((Class . Console)(Name . Net-Yaroze)(Year . 1997)(Manufacturer/Country . Sony ))
((Class . Console)(Name . Sega-Saturn)(Year . 1994)(Manufacturer/Country . Sega ))
((Class . Console)(Name . 3DO-Interactive-Multiplayer)(Year . 1993)(Manufacturer/Country . Panasonic  / Sanyo / GoldStar ))
((Class . Console)(Name . Amiga-CD32)(Year . 1993)(Manufacturer/Country . Commodore ))
((Class . Console)(Name . Casio-Loopy)(Year . 1995)(Manufacturer/Country . Casio ))
((Class . Console)(Name . Playdia)(Year . 1994)(Manufacturer/Country . Bandai ))
((Class . Console)(Name . CPS-Changer)(Year . 1994)(Manufacturer/Country . Capcom ))
((Class . Console)(Name . Nintendo-64)(Year . 1996)(Manufacturer/Country . Nintendo ))
((Class . Console)(Name . Nintendo-64DD)(Year . 1999)(Manufacturer/Country . Nintendo ))
((Class . Console)(Name . Sega-32X)(Year . 1994)(Manufacturer/Country . Sega ))
((Class . Console)(Name . Dreamcast)(Year . 1998)(Manufacturer/Country . Sega ))
((Class . Console)(Name . Nuon)(Year . 2000)(Manufacturer/Country . VM-Labs ))
((Class . Console)(Name . PlayStation-2)(Year . 2000)(Manufacturer/Country . Sony ))
((Class . Console)(Name . GameCube)(Year . 2001)(Manufacturer/Country . Nintendo ))
((Class . Console)(Name . Game-Boy-Player)(Year . 2003)(Manufacturer/Country . Nintendo ))
((Class . Console)(Name . iQue-Player)(Year . 2003)(Manufacturer/Country . Nintendo ))
((Class . Console)(Name . Panasonic-Q/Q-Game-Boy-Player)(Year . 2001)(Manufacturer/Country . Nintendo  / Panasonic ))
((Class . Console)(Name . Xbox)(Year . 2001)(Manufacturer/Country . Microsoft ))
((Class . Console)(Name . PSX)(Year . 2003)(Manufacturer/Country . Sony ))
((Class . Console)(Name . XaviX-Port)(Year . 2004)(Manufacturer/Country . SSD-Company))
((Class . Console)(Name . DISCover)(Year . 2004)(Manufacturer/Country . Digital-Interactive-Systems-Corporation))
((Class . Console)(Name . Leapster-TV)(Year . 2005)(Manufacturer/Country . LeapFrog ))
((Class . Console)(Name . V . Smile)(Year . 2005)(Manufacturer/Country . VTech ))
((Class . Console)(Name . GoGo-TV-Video-Vision)(Year . 2005)(Manufacturer/Country . Manley / Toy-Quest))
((Class . Console)(Name . Buzztime-Home-Trivia-System)(Year . 2005)(Manufacturer/Country . NTN-Buzztime  / Cadaco))
((Class . Console)(Name . Sega-Beena)(Year . 2005)(Manufacturer/Country . Sega ))
((Class . Console)(Name . Game-Wave)(Year . 2005)(Manufacturer/Country . ZAPiT ))
((Class . Console)(Name . Xbox-360)(Year . 2005)(Manufacturer/Country . Microsoft ))
((Class . Console)(Name . HyperScan)(Year . 2006)(Manufacturer/Country . Mattel ))
((Class . Console)(Name . ION)(Year . 2006)(Manufacturer/Country . Playskool  / Hasbro ))
((Class . Console)(Name . Wii)(Year . 2006)(Manufacturer/Country . Nintendo ))
((Class . Console)(Name . PlayStation-3)(Year . 2006)(Manufacturer/Country . Sony ))
((Class . Console)(Name . I-Can-Play-Piano)(Year . 2006)(Manufacturer/Country . Fisher-Price ))
((Class . Console)(Name . V . Flash)(Year . 2006)(Manufacturer/Country . VTech ))
((Class . Console)(Name . V . Smile-V-Motion)(Year . 2008)(Manufacturer/Country . VTech ))
((Class . Console)(Name . V . Smile-Baby)(Year . 2009)(Manufacturer/Country . VTech ))
((Class . Console)(Name . Vmigo-TV-Docking-System)(Year . 2006)(Manufacturer/Country . Jakks-Pacific ))
((Class . Console)(Name . Telestory)(Year . 2006)(Manufacturer/Country . Jakks-Pacific ))
((Class . Console)(Name . Clickstart-My-First-Computer)(Year . 2007)(Manufacturer/Country . LeapFrog ))
((Class . Console)(Name . I-Can-Play-Guitar)(Year . 2007)(Manufacturer/Country . Fisher-Price ))
((Class . Console)(Name . Smart-Cycle)(Year . 2007)(Manufacturer/Country . Fisher-Price ))
((Class . Console)(Name . EVO-Smart-Console)(Year . 2008)(Manufacturer/Country . Envizions ))
((Class . Console)(Name . Sega-Firecore)(Year . 2009)(Manufacturer/Country . AtGames ))
((Class . Console)(Name . Zeebo)(Year . 2009)(Manufacturer/Country . Zeebo-Inc .  ))
((Class . Console)(Name . Zippity)(Year . 2009)(Manufacturer/Country . LeapFrog ))
((Class . Console)(Name . Sega-Zone)(Year . 2010)(Manufacturer/Country . Atgames / Sega ))
((Class . Console)(Name . Eedoo-CT510)(Year . 2012)(Manufacturer/Country . Lenovo  / Eedoo ))
((Class . Console)(Name . Wii-U)(Year . 2012)(Manufacturer/Country . Nintendo ))
((Class . Console)(Name . PlayStation-4)(Year . 2013)(Manufacturer/Country . Sony ))
((Class . Console)(Name . Xbox-One)(Year . 2013)(Manufacturer/Country . Microsoft ))
((Class . Console)(Name . RetroN-5)(Year . 2014)(Manufacturer/Country . Hyperkin))
((Class . Console)(Name . LeapTV)(Year . 2014)(Manufacturer/Country . LeapFrog-Enterprises ))
((Class . Console)(Name . Karaoke-Ranking-Party)(Year . 2015)(Manufacturer/Country . Bandai ))
((Class . Console)(Name . InnoTV)(Year . 2015)(Manufacturer/Country . VTech ))
((Class . Console)(Name . Tomahawk-F1)(Year . 2016)(Manufacturer/Country . FUZE-Entertainment ))
((Class . Predicado)(etiq . Reproduce)(Game . The-Legend-of-Zelda-Ocarina-of-Time)(Console . Nintendo-64))
((Class . Predicado)(etiq . Reproduce)(Game . Tetris)(Console . Elektronika-60))
((Class . Predicado)(etiq . Reproduce)(Game . Super-Mario-64)(Console . Nintendo-64))
((Class . Predicado)(etiq . Reproduce)(Game . The-Legend-of-Zelda-A-Link-to-the-Past)(Console . Super-NES))
((Class . Predicado)(etiq . Reproduce)(Game . Chrono-Trigger)(Console . Super-NES))
((Class . Predicado)(etiq . Reproduce)(Game . Final-Fantasy-VII)(Console . PlayStation))
((Class . Predicado)(etiq . Reproduce)(Game . Street-Fighter-II)(Console . Arcade))
((Class . Predicado)(etiq . Reproduce)(Game . Half-Life-2)(Console . PC))
((Class . Predicado)(etiq . Reproduce)(Game . GoldenEye-007)(Console . Nintendo-64))
((Class . Predicado)(etiq . Reproduce)(Game . Super-Mario-World)(Console . Super-NES))
((Class . Predicado)(etiq . Reproduce)(Game . Super-Metroid)(Console . Super-NES))
((Class . Predicado)(etiq . Reproduce)(Game . Resident-Evil-4)(Console . GameCube))
((Class . Predicado)(etiq . Reproduce)(Game . Metal-Gear-Solid)(Console . PlayStation))
((Class . Predicado)(etiq . Reproduce)(Game . Super-Mario-Kart)(Console . Super-NES))
((Class . Predicado)(etiq . Reproduce)(Game . Castlevania-Symphony-of-the-Night)(Console . PlayStation))
((Class . Predicado)(etiq . Reproduce)(Game . Super-Mario-Bros . -3)(Console . NES))
((Class . Predicado)(etiq . Reproduce)(Game . Super-Mario-Bros . )(Console . NES))
((Class . Predicado)(etiq . Reproduce)(Game . BioShock)(Console . PC, Xbox-360))
((Class . Predicado)(etiq . Reproduce)(Game . Final-Fantasy-VI)(Console . Super-NES))
((Class . Predicado)(etiq . Reproduce)(Game . Pokémon-Red and Blue)(Console . Game-Boy))
((Class . Predicado)(etiq . Reproduce)(Game . StarCraft)(Console . PC))
((Class . Predicado)(etiq . Reproduce)(Game . Shadow-of-the-Colossus)(Console . PlayStation-2))
((Class . Predicado)(etiq . Reproduce)(Game . SoulCalibur)(Console . Dreamcast))
((Class . Predicado)(etiq . Reproduce)(Game . The-Legend-of-Zelda)(Console . NES))
((Class . Predicado)(etiq . Reproduce)(Game . Doom)(Console . PC))
((Class . Predicado)(etiq . Reproduce)(Game . Half-Life)(Console . PC))
((Class . Predicado)(etiq . Reproduce)(Game . Diablo-II)(Console . PC))
((Class . Predicado)(etiq . Reproduce)(Game . World-of-Warcraft)(Console . PC))
((Class . Predicado)(etiq . Reproduce)(Game . Metroid-Prime)(Console . GameCube))
((Class . Predicado)(etiq . Reproduce)(Game . Super-Mario-World-2-Yoshis-Island)(Console . Super-NES))
((Class . Predicado)(etiq . Reproduce)(Game . Resident-Evil)(Console . PlayStation))
((Class . Predicado)(etiq . Reproduce)(Game . Deus-Ex)(Console . PC))
((Class . Predicado)(etiq . Reproduce)(Game . Pac-Man)(Console . Arcade))
((Class . Predicado)(etiq . Reproduce)(Game . Donkey-Kong)(Console . Arcade))
((Class . Predicado)(etiq . Reproduce)(Game . Contra)(Console . Arcade))
((Class . Predicado)(etiq . Reproduce)(Game . Halo-Combat-Evolved)(Console . Xbox))
((Class . Predicado)(etiq . Reproduce)(Game . Space-Invaders)(Console . Arcade))
((Class . Predicado)(etiq . Reproduce)(Game . Sonic-the-Hedgehog)(Console . Genesis/Mega-Drive))
((Class . Predicado)(etiq . Reproduce)(Game . Grim-Fandango)(Console . PC))
((Class . Predicado)(etiq . Reproduce)(Game . The-Legend-of-Zelda-Majoras-Mask)(Console . Nintendo-64))
((Class . Predicado)(etiq . Reproduce)(Game . Super-Smash-Bros . -Melee)(Console . GameCube))
((Class . Predicado)(etiq . Reproduce)(Game . The-Legend-of-Zelda-The-Wind-Waker)(Console . GameCube))
((Class . Predicado)(etiq . Reproduce)(Game . Mass-Effect-2)(Console . PC, Xbox-360))
((Class . Predicado)(etiq . Reproduce)(Game . Counter-Strike)(Console . PC))
((Class . Predicado)(etiq . Reproduce)(Game . The-Last-of-Us)(Console . PlayStation-3))
((Class . Predicado)(etiq . Reproduce)(Game . Punch-Out!!)(Console . Arcade))
((Class . Predicado)(etiq . Reproduce)(Game . EarthBound)(Console . Super-NES))
((Class . Predicado)(etiq . Reproduce)(Game . Star-Wars-Knights-of-the-Old-Republic)(Console . Xbox))
((Class . Predicado)(etiq . Reproduce)(Game . Portal)(Console . PC, Xbox-360))
((Class . Predicado)(etiq . Reproduce)(Game . Super-Mario-Galaxy)(Console . Wii))
((Class . Predicado)(etiq . Reproduce)(Game . Portal-2)(Console . PC, PlayStation-3, Xbox-360))
((Class . Predicado)(etiq . Reproduce)(Game . Secret-of-Mana)(Console . Super-NES))
((Class . Predicado)(etiq . Reproduce)(Game . The-Legend-of-Zelda-Links-Awakening)(Console . Game-Boy))
((Class . Predicado)(etiq . Reproduce)(Game . Star-Fox-64)(Console . Nintendo-64))
((Class . Predicado)(etiq . Reproduce)(Game . Resident-Evil-2)(Console . PlayStation))
((Class . Predicado)(etiq . Reproduce)(Game . Perfect-Dark)(Console . Nintendo-64))
((Class . Predicado)(etiq . Reproduce)(Game . Metal-Gear-Solid-2-Sons-of-Liberty)(Console . PlayStation-2))
((Class . Predicado)(etiq . Reproduce)(Game . Call-of-Duty-4-Modern-Warfare)(Console . PC, PlayStation-3, Xbox-360))
((Class . Predicado)(etiq . Reproduce)(Game . The-Elder-Scrolls-V-Skyrim)(Console . PC, PlayStation-3, Xbox-360))
((Class . Predicado)(etiq . Reproduce)(Game . Dark-Souls)(Console . PlayStation-3, Xbox-360))
((Class . Predicado)(etiq . Reproduce)(Game . Ms . -Pac-Man)(Console . Arcade))
((Class . Predicado)(etiq . Reproduce)(Game . Metroid)(Console . NES))
((Class . Predicado)(etiq . Reproduce)(Game . Advance-Wars)(Console . Game-Boy-Advance))
((Class . Predicado)(etiq . Reproduce)(Game . Ico)(Console . PlayStation-2))
((Class . Predicado)(etiq . Reproduce)(Game . Silent-Hill-2)(Console . PlayStation-2))
((Class . Predicado)(etiq . Reproduce)(Game . Prince-of-Persia-The-Sands-of-Time)(Console . PlayStation-2))
((Class . Predicado)(etiq . Reproduce)(Game . Double-Dragon)(Console . Arcade))
((Class . Predicado)(etiq . Reproduce)(Game . Mega-Man-2)(Console . NES))
((Class . Predicado)(etiq . Reproduce)(Game . Final-Fantasy-IV)(Console . Super-NES))
((Class . Predicado)(etiq . Reproduce)(Game . Gunstar-Heroes)(Console . Genesis/Mega-Drive))
((Class . Predicado)(etiq . Reproduce)(Game . Shenmue)(Console . Dreamcast))
((Class . Predicado)(etiq . Reproduce)(Game . Final-Fantasy-X)(Console . PlayStation-2))
((Class . Predicado)(etiq . Reproduce)(Game . Grand-Theft-Auto-III)(Console . PlayStation-2))
((Class . Predicado)(etiq . Reproduce)(Game . Metal-Gear-Solid-3-Snake-Eater)(Console . PlayStation-2))
((Class . Predicado)(etiq . Reproduce)(Game . Okami)(Console . PlayStation-2))
((Class . Predicado)(etiq . Reproduce)(Game . Galaga)(Console . Arcade))
((Class . Predicado)(etiq . Reproduce)(Game . Star-Wars-TIE-Fighter)(Console . PC))
((Class . Predicado)(etiq . Reproduce)(Game . Tomb-Raider)(Console . Saturn))
((Class . Predicado)(etiq . Reproduce)(Game . Final-Fantasy-Tactics)(Console . PlayStation))
((Class . Predicado)(etiq . Reproduce)(Game . Grand-Theft-Auto-San-Andreas)(Console . PlayStation-2))
((Class . Predicado)(etiq . Reproduce)(Game . Grand-Theft-Auto-V)(Console . PlayStation-3, Xbox-360))
((Class . Predicado)(etiq . Reproduce)(Game . Red-Dead-Redemption)(Console . PlayStation-3, Xbox-360))
((Class . Predicado)(etiq . Reproduce)(Game . OutRun)(Console . Arcade))
((Class . Predicado)(etiq . Reproduce)(Game . R-Type)(Console . Arcade))
((Class . Predicado)(etiq . Reproduce)(Game . Fallout-3)(Console . PC, PlayStation-3, Xbox-360))
((Class . Predicado)(etiq . Reproduce)(Game . Uncharted-2-Among-Thieves)(Console . PlayStation-3))
((Class . Predicado)(etiq . Reproduce)(Game . Minecraft)(Console . PC))
((Class . Predicado)(etiq . Reproduce)(Game . Sonic-the-Hedgehog-2)(Console . Genesis/Mega-Drive))
((Class . Predicado)(etiq . Reproduce)(Game . Daytona-USA)(Console . Arcade))
((Class . Predicado)(etiq . Reproduce)(Game . Journey)(Console . PlayStation-3))
((Class . Predicado)(etiq . Reproduce)(Game . Batman-Arkham-City)(Console . PlayStation-3, Xbox-360))
((Class . Predicado)(etiq . Reproduce)(Game . Super-Mario-Galaxy-2)(Console . Wii))
((Class . Predicado)(etiq . Reproduce)(Game . Nights-into-Dreams .  .  . )(Console . Saturn))
((Class . Predicado)(etiq . Reproduce)(Game . Xenogears)(Console . PlayStation))
((Class . Predicado)(etiq . Reproduce)(Game . Kingdom-Hearts)(Console . PlayStation-2))
((Class . Predicado)(etiq . Reproduce)(Game . Grand-Theft-Auto-IV)(Console . PlayStation-3, Xbox-360))
((Class . Predicado)(etiq . Reproduce)(Game . Robotron)(Console . Arcade))
((Class . Predicado)(etiq . Reproduce)(Game . Elite)(Console . BBC-Micro))
((Class . Predicado)(etiq . Reproduce)(Game . Tecmo-Bowl)(Console . Arcade))
((Class . Predicado)(etiq . Reproduce)(Game . Skies-of-Arcadia)(Console . Dreamcast))
((Class . Predicado)(etiq . Reproduce)(Game . Hotline-Miami)(Console . PC))